// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CppCaseZeroZero
double CppCaseZeroZero(double alpha, double beta, double kappa, double B1, double B2, double B3);
RcppExport SEXP _ev_trawl_cpp_CppCaseZeroZero(SEXP alphaSEXP, SEXP betaSEXP, SEXP kappaSEXP, SEXP B1SEXP, SEXP B2SEXP, SEXP B3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type B1(B1SEXP);
    Rcpp::traits::input_parameter< double >::type B2(B2SEXP);
    Rcpp::traits::input_parameter< double >::type B3(B3SEXP);
    rcpp_result_gen = Rcpp::wrap(CppCaseZeroZero(alpha, beta, kappa, B1, B2, B3));
    return rcpp_result_gen;
END_RCPP
}
// CppCaseOneZero
double CppCaseOneZero(NumericVector xs, double alpha, double beta, double kappa, double B1, double B2, double B3);
RcppExport SEXP _ev_trawl_cpp_CppCaseOneZero(SEXP xsSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP kappaSEXP, SEXP B1SEXP, SEXP B2SEXP, SEXP B3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type B1(B1SEXP);
    Rcpp::traits::input_parameter< double >::type B2(B2SEXP);
    Rcpp::traits::input_parameter< double >::type B3(B3SEXP);
    rcpp_result_gen = Rcpp::wrap(CppCaseOneZero(xs, alpha, beta, kappa, B1, B2, B3));
    return rcpp_result_gen;
END_RCPP
}
// CppCaseOneOne
double CppCaseOneOne(NumericVector xs, double alpha, double beta, double kappa, double B1, double B2, double B3);
RcppExport SEXP _ev_trawl_cpp_CppCaseOneOne(SEXP xsSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP kappaSEXP, SEXP B1SEXP, SEXP B2SEXP, SEXP B3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type B1(B1SEXP);
    Rcpp::traits::input_parameter< double >::type B2(B2SEXP);
    Rcpp::traits::input_parameter< double >::type B3(B3SEXP);
    rcpp_result_gen = Rcpp::wrap(CppCaseOneOne(xs, alpha, beta, kappa, B1, B2, B3));
    return rcpp_result_gen;
END_RCPP
}
// CppCaseSeparator
double CppCaseSeparator(NumericVector xs, double alpha, double beta, double kappa, double B1, double B2, double B3);
RcppExport SEXP _ev_trawl_cpp_CppCaseSeparator(SEXP xsSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP kappaSEXP, SEXP B1SEXP, SEXP B2SEXP, SEXP B3SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xs(xsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type B1(B1SEXP);
    Rcpp::traits::input_parameter< double >::type B2(B2SEXP);
    Rcpp::traits::input_parameter< double >::type B3(B3SEXP);
    rcpp_result_gen = Rcpp::wrap(CppCaseSeparator(xs, alpha, beta, kappa, B1, B2, B3));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _ev_trawl_cpp_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ev_trawl_cpp_CppCaseZeroZero", (DL_FUNC) &_ev_trawl_cpp_CppCaseZeroZero, 6},
    {"_ev_trawl_cpp_CppCaseOneZero", (DL_FUNC) &_ev_trawl_cpp_CppCaseOneZero, 7},
    {"_ev_trawl_cpp_CppCaseOneOne", (DL_FUNC) &_ev_trawl_cpp_CppCaseOneOne, 7},
    {"_ev_trawl_cpp_CppCaseSeparator", (DL_FUNC) &_ev_trawl_cpp_CppCaseSeparator, 7},
    {"_ev_trawl_cpp_rcpp_hello_world", (DL_FUNC) &_ev_trawl_cpp_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_ev_trawl_cpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
