# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
CppCaseZeroZero <- function(alpha, beta, kappa, B1, B2, B3) {
    .Call(`_ev_trawl_cpp_CppCaseZeroZero`, alpha, beta, kappa, B1, B2, B3)
}

#' @export
CppCaseOneZero <- function(xs, alpha, beta, kappa, B1, B2, B3) {
    .Call(`_ev_trawl_cpp_CppCaseOneZero`, xs, alpha, beta, kappa, B1, B2, B3)
}

#' @export
CppCaseOneOne <- function(xs, alpha, beta, kappa, B1, B2, B3) {
    .Call(`_ev_trawl_cpp_CppCaseOneOne`, xs, alpha, beta, kappa, B1, B2, B3)
}

#' @export
CppCaseSeparator <- function(xs, alpha, beta, kappa, B1, B2, B3) {
    .Call(`_ev_trawl_cpp_CppCaseSeparator`, xs, alpha, beta, kappa, B1, B2, B3)
}

rcpp_hello_world <- function() {
    .Call(`_ev_trawl_cpp_rcpp_hello_world`)
}

